steps:

  - label: ":node: Run Tests"
    command:
      - npm install && npm run test

  - wait

  - label: ":books: Create the ZIP file"
    command:
      - npm install && 7z a -tzip ./archives/function.zip ./
    artifact_paths:
      - "archives/function.zip"

  - block: ":rocket: Deploy to Lambda"

  - wait

  - label: ":aws-lambda: Upload ZIP file"
    command:
      - buildkite-agent artifact download "*" .
      - aws lambda update-function-code --function-name buildkite-basics-lambda --zip-file fileb://$BUILDKITE_BUILD_CHECKOUT_PATH/archives/function.zip